# Schema for configuration files of the Paragraphs layout builder module.

node.type.*.third_party.merlb:
  type: mapping
  label: "Per-content type merlb settings"
  mapping:
    enabled:
      type: boolean
      label: "Enabled"
    field_names:
      type: string
      label: "Field to be processed by merlb"
