# Schema for configuration files of the Paragraphs entity layout module.

node.type.*.third_party.pel:
  type: mapping
  label: 'Per-content type PEL settings'
  mapping:
    enabled:
      type: boolean
      label: 'PEL Enabled'
    field_name:
      type: string
      label: 'Field to be processed by PEL'
