# Schema for configuration files of the Paragraphs layout builder module.

node.type.*.third_party.plb:
  type: mapping
  label: "Per-content type paragraphs layout builder settings"
  mapping:
    enabled:
      type: boolean
      label: "Enabled"
    field_name:
      type: string
      label: "Field to be processed by PLB"
